config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end

  resource :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :price_in_cents, presence: true

  has_many :reviews 

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :comment, presence: true
  validates :product_id, presence: true

  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]
    if @product.save
      flash[:notice] = "Product added successfully"
      redirect_to product_url(@product.id)
    else
      flash[:alert] = "Failed to create product"
      render 'products/new'
    end
  end

  def update
    @product = Product.find(params[:id])
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]
    if @product.save
      flash[:notice] = "Product updated sucessfully"
      redirect_to product_url(@product.id)
    else
      flash[:alert] = "Failed to create product"
      render "products/edit", notice: "Product updated"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: "Product deleted"
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new
    @review.comment = params[:review][:comment]
    @review.product_id = params[:product_id]

    if @review.save
			redirect_to product_path(id: params[:product_id])
		else
			flash[:warning] = @review.errors.full_messages
		 	redirect_to product_path(id: params[:product_id])
		end
  end

  def edit
    @review = Review.find(params[:id])
    @product = @review.product
  end

  def update
    @review = Review.find(params[:id])
    @product = @review.product
    @review.comment = params[:review][:comment]

    if @review.save
      redirect_to product_path(id: params[:product_id])
    else
    	flash[:warning] = @review.errors.full_messages
      render edit_product_review_path #this won't work anyway.. need params
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review successfully deleted"
    redirect_to product_path(id: params[:product_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to products_path, notice: "Logged in!"
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new

    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      redirect_to root_path
    else
      render new_users_path
    end    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%=link_to('Home', products_path)%>
      <%=link_to('New Product', new_product_path)%>

      <p class="userinfo">
        <% if current_user %>
          Signed in as <%= current_user.email %>. <%= link_to "Log out", sessions_path("current"), :method => :delete %>
        <% else %>
          <%= link_to("Log in", new_sessions_path) %> or <%= link_to "Sign up", new_users_path %>
        <% end %>
      </p>
    </nav>

    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>



  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <div class="field">
    <p><%= f.label :name %> </p>
    <p><%= f.text_field :name %></p>
  </div>

  <div class="field">
    <p><%= f.label :description %> </p>
    <p><%= f.text_field :description %></p>
  </div>

  <div class="field">
    <p><%= f.label :price_in_cents %> </p>
    <p><%= f.text_field :price_in_cents %></p>
  </div>

  <div class="field">
    <p><%= f.submit %> </p>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Products?<h1>
<h2>Modify a product below!</h2>
<%= render '/products/form' %>

app/views/products/index.html.erb
<h1>Products</h1>
<h2>Browse our list of products below</h2>
  <% @products.each do |p| %>
  <h3><%= p.name %></h3>
  <h3><%= p.description %></h3>
  <h3><%= p.price_in_dollars %></h3>
  <%= link_to("Show", product_path(p.id))%>
  <% end %>

app/views/products/new.html.erb
<h1>New Products?<h1>
<h2>Add a product!</h2>
<%= render '/products/form' %>

app/views/products/show.html.erb
<h1><%=@product.name%></h1>
<ul>
  <li><%=@product.name%></li>
  <li><%=@product.description%></li>
  <li><%=@product.price_in_dollars%></li>
</ul>

<h2>Reviews</h2>
  <% @product.reviews.each do |r| %>
    <ul>
      <li><%= r.comment %></li>
      <li><%= r.created_at %></li>
      <li><%= link_to('Edit Review') %></li>
    </ul>
  <% end %>

<%= render '/reviews/form' %>

<%= link_to("Home", products_path) %>

<%= link_to("Edit", edit_product_path(@product.id)) %>

<%= link_to("Delete Product", product_path, :method => :delete, data: {confirm: "Are you sure you want to delete this product: '#{ @product.name }' ?"}) %>

app/views/reviews/_form.html.erb
<h4>New Review</h4>

<%= form_for([@product, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= render '/reviews/form' %>
<%= link_to("Delete Review", product_review_path, :method => :delete, data: {confirm: "Are you sure you want to delete this product: '#{ @product.name }' ?"})%>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div class="field">
    <p><%= f.label :email %> </p>
    <p><%= f.text_field :email %></p>
  </div>

  <div class="field">
    <p><%= f.label :password %> </p>
    <p><%= f.text_field :password %></p>
  </div>

  <div class="field">
    <p><%= f.label :password_confirmation %> </p>
    <p><%= f.text_field :password_confirmation %></p>
  </div>

  <div class="field">
    <p><%= f.submit %> </p>
  </div>
<% end %>